
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Site specific settings
title: "Brandon Sansone"
name: "Brandon Sansone"
email: "sansonebrandon@gmail.com"
description: "Brandon Sansone, IT professional and enthusiast of all things computer related, is a graduate of the Illinois Institute of Technology, receiving his Bachelor's degree in Information Technology & Management in May 2016."
baseurl: ''
url: 'http://bsansone.github.io/'

# Site general settings
lang: "en"
ssl: false # It will redirect to https

# Media
github_username:
facebook:  

# Build settings
markdown: 
